// Product catalog para uso compartido en múltiples componentes
export const PRODUCTS = [
  { name: "Duo-60 Fusion", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575568/Duo-60fusion_xhsjhs.png", slug: "/duo-60-fusion" },
  { name: "Alpha Glow", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575532/alphaglow_jwu8mg.png", slug: "/alphaglow" },
  { name: "SOS Burn", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575596/sosburn_g2ui2b.png", slug: "/sosburn" },
  { name: "SOS Burn Clean", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575602/sosburnclear_iuyqej.png", slug: "/sosburn-clear" },
  { name: "SOS Burn Sensitive", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575600/sosburnsensitive_dfsrs1.png", slug: "/sosburn-sensitive" },
  { name: "Prime Rose", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575597/primerose_jk26zj.png", slug: "/primrose" },
  { name: "Lida Booster", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575576/Lidabooster_xd5mo9.png", slug: "/lidabooster" },
  { name: "Lipo HD 360", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575584/lipohd_zg9lxy.png", slug: "/lipohd" },
  { name: "Chupa Panza", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575545/chupapanza_m7zfgs.png", slug: "/chupapanza" },
  { name: "Higa2", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575578/higa2_bzokur.png", slug: "/higa2" },
  { name: "Serenity", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575589/serenity_mnncq7.png", slug: "/serenity" },
  { name: "Floryva", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575563/floryva_nb3b0y.png", slug: "/floryva" },
  { name: "Maca Premium", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575588/macapremium_s6k65z.png", slug: "/macapremium" },
  { name: "Encimax", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575578/encimax_kuhluy.png", slug: "/encimax" },
  { name: "Fat Blazer", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761578536/fatblazer_vw1fks.png", slug: "/fatblazer" },
  { name: "Slim Coffee Thermogenic", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575594/slimcoffe_taahyd.png", slug: "/slimcoffee" },
  { name: "Apple Cider Vinagre", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575550/applecyder_xxg1ps.png", slug: "/applecyder" },
  { name: "30-Day Detox", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575526/30daydetox_roziws.png", slug: "/30daydetox" },
  { name: "Colit 6", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575551/colit6_te7kpi.png", slug: "/colit6" },
  { name: "CM Push up Men", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575544/cmpushup_ncxzh6.png", slug: "/cmpushupmen" },
  { name: "Maxi Fibra", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761549733/catalogo-mvv-natural-18_bj3iwu.webp", slug: "/maxifibra" },
  { name: "Magic Booty Up", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761549733/catalogo-mvv-natural-26_qacvkr.webp", slug: "/magicbootyup" },
  { name: "Colágeno & Biotina", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761549733/catalogo-mvv-natural-17_qhlkxa.webp", slug: "/colageno-biotina" },
  { name: "15 Day Detox Tea", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761549733/catalogo-mvv-natural-15_ojfmth.webp", slug: "/15daydetoxtea" },
  { name: "3 Day Reset", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761549733/catalogo-mvv-natural-16_ydcn0m.webp", slug: "/3dayreset" },
  { name: "Protein Body", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761549733/catalogo-mvv-natural-9_x4mbwd.webp", slug: "/proteinbody" },
  { name: "Mens Exotic", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761549733/catalogo-mvv-natural-24_cayyap.webp", slug: "/mensexotic" },
  { name: "Thyroid Support", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761549733/catalogo-mvv-natural-27_wezqrg.webp", slug: "/thyroid-support" },
  { name: "H-Flex", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761549733/catalogo-mvv-natural-8_jduebo.webp", slug: "/hflex" },
  { name: "30 Fusion Xtreme", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761575561/duo30fusion_t59hk3.png", slug: "/30fusion" },
  { name: "Slim Shake", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761549733/catalogo-mvv-natural-30_nal8d7.webp", slug: "/slimshake" },
  { name: "Blueberry Colágeno Hidrolizado", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761549733/catalogo-mvv-natural-31_qsewuj.webp", slug: "/blueberry-colageno" },
  { name: "Bikini Strong", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761549733/catalogo-mvv-natural-32_qqgu08.webp", slug: "/bikinstrong" },
  { name: "Meizitang Soft Gel", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761549733/catalogo-mvv-natural-34_nja22n.webp", slug: "/meizitang" },
  { name: "Body Shape", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761549733/catalogo-mvv-natural-38_stdnup.webp", slug: "/bodyshape" },
  { name: "Slim24", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761549733/catalogo-mvv-natural-39_ylthvp.webp", slug: "/slim24" },
  { name: "Li-Da Daidahua Slimming Tea", image: "https://res.cloudinary.com/dsulhqvza/image/upload/f_auto,q_auto,w_1200/v1761549733/catalogo-mvv-natural-36_mj6ljw.webp", slug: "/lidatea" }
];

